# 使用 Node.js 镜像作为基础镜像
FROM node:18

# Install foundry
RUN curl -L https://foundry.paradigm.xyz | bash

# 设置工作目录
WORKDIR /app

# 复制项目的所有文件至工作目录
COPY . .

# 安装项目依赖
RUN cd contracts && yarn install --verbose

WORKDIR /app/contracts

# Set the entrypoint to the forge deployment command
ENTRYPOINT ["yarn"]